---
collections:
  # Install MongoDB Collection from Ansible Galaxy.
  - name: community.mongodb
    version: 1.3.1
  # More collections needed because of changes in Ansible 4.2+
  - name: community.docker
    version: >=1.9.1
