Vagrant.configure("2") do |config|
  MONGOD_HOSTS=6
  MONGOS_HOSTS=3

  (1..MONGOD_HOSTS).each do |mongod|
    node_name = "mongodb#{mongod}"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vbguest.installer_options = { allow_kernel_upgrade: true }
    config.vm.define node_name do |mongod_node|
      mongod_node.vm.box = "centos/8"
      mongod_node.vm.network "private_network", ip: "192.168.43.#{200 + mongod}"
      mongod_node.vm.hostname = node_name
      mongod_node.vm.provider :virtualbox do |vbox|
        vbox.memory = 1024
        vbox.linked_clone = true
        vbox.name = node_name
      end

    config.vm.provision "allow_guest_host_resolution",
        type: "shell",
        inline: 'yum install -y epel-release; yum install -y avahi nss-mdns systemd; systemctl restart avahi-daemon'

    if mongod == MONGOD_HOSTS
      mongod_node.vm.provision :ansible do |ansible|
        ansible.groups = {
          "mongodb" => ["mongodb1","mongodb2","mongodb3","mongodb4","mongodb5","mongodb6"],
          "rs0" => ["mongodb1","mongodb2","mongodb3"],
          "rs1" => ["mongodb4","mongodb5","mongodb6"],
          "mongos" => ["mongos1","mongos2","mongos3"],
          "rs0:vars" => {"repl_set_name" => "rs0", "members" => ["mongodb1.local:27018", "mongodb2.local:27018", "mongodb3.local:27018"]},
          "rs1:vars" => {"repl_set_name" => "rs1", "members" => ["mongodb4.local:27018", "mongodb5.local:27018", "mongodb6.local:27018"]},
          "mongos:vars" => {"repl_set_name" => "cfg", "members" => ["mongos1.local:27019", "mongos2.local:27019", "mongos3.local:27019"]},
        }
        ansible.raw_arguments = "--ask-vault-pass"
        ansible.become = true
        ansible.limit = "mongodb" # Connect to all mongodb hosts
        ansible.playbook = "mongodb.yml"
      end
    end
  end
end

    (1..MONGOS_HOSTS).each do |mongos|
      node_name = "mongos#{mongos}"
      config.vm.synced_folder ".", "/vagrant", disabled: true
      config.vbguest.installer_options = { allow_kernel_upgrade: true }
      config.vm.define node_name do |mongos_node|
        mongos_node.vm.box = "centos/8"
        mongos_node.vm.network "private_network", ip: "192.168.43.#{100 + mongos}"
        mongos_node.vm.hostname = node_name
        mongos_node.vm.provider :virtualbox do |vbox|
          vbox.memory = 1024
          vbox.linked_clone = true
          vbox.name = node_name
        end

      config.vm.provision "allow_guest_host_resolution",
          type: "shell",
          inline: 'yum install -y epel-release; yum install -y avahi nss-mdns systemd; systemctl restart avahi-daemon'

      if mongos == MONGOS_HOSTS
        mongos_node.vm.provision :ansible do |ansible|
          ansible.groups = {
            "mongodb" => ["mongodb1","mongodb2","mongodb3","mongodb4","mongodb5","mongodb6"],
            "rs0" => ["mongodb1","mongodb2","mongodb3"],
            "rs1" => ["mongodb4","mongodb5","mongodb6"],
            "mongos" => ["mongos1","mongos2","mongos3"],
          }
          ansible.raw_arguments = "--ask-vault-pass"
          ansible.become = true
          ansible.limit = "mongos" # Connect to all mongos hosts
          ansible.playbook = "mongos.yml"
        end
      end
    end
  end
end
