---
- name: Disable the Balancer
  hosts: mongos
  vars_files:
    - ../vars/main.yml
    - ../sharded_cluster/vault.yml

  tasks:

    - name: Disable the Balancer
      community.mongodb.mongodb_balancer:
        state: stopped
        login_user: "{{ admin_user }}"
        login_password: "{{ admin_user_password }}"
        login_port: "{{ mongos_port }}"
      run_once: yes

- name: Upgrade SECONDARY mongod config servers
  hosts: mongos
  gather_facts: yes
  become: yes
  serial: 1
  vars_files:
    - ../vars/main.yml
    - ../sharded_cluster/vault.yml
  vars:
    required_packages:
      - "yum-plugin-versionlock"
    current_mongodb_version: "4.2"
    target_mongodb_version: "4.4"

  # Process is based on the following offical documentation...
  # https://docs.mongodb.com/manual/release-notes/4.2-upgrade-sharded-cluster/
  tasks:

    - name: Set mongod_port to 27019
      set_fact:
        mongod_port: 27019

    - import_tasks: ../shared_tasks/get_primary.yml

    - name: Upgrade SECONDARY config servers first
      block:

        - import_tasks: ../shared_tasks/upgrade_mongod.yml

        - name: Ensure that current replicaset state is good
          community.mongodb.mongodb_status:
            login_user: "{{ admin_user }}"
            login_password: "{{ admin_user_password }}"
            login_port: "{{ mongod_port }}"
            replica_set: "{{ repl_set_name }}"
            poll: 3
            interval: 10
      when: inventory_hostname_short != primary

- name: Upgrade PRIMARY mongod config server
  hosts: mongos
  gather_facts: yes
  become: yes
  vars_files:
    - ../vars/main.yml
    - ../sharded_cluster/vault.yml
  vars:
    required_packages:
      - "yum-plugin-versionlock"
    current_mongodb_version: "4.2"
    target_mongodb_version: "4.4"

  tasks:

    - name: Set mongod_port to 27019
      set_fact:
        mongod_port: 27019

    - import_tasks: ../shared_tasks/get_primary.yml

    - name: Upgrade PRIMARY Config Server
      block:

        - name: Stepdown primary
          community.mongodb.mongodb_stepdown:
            login_user: "{{ admin_user }}"
            login_password: "{{ admin_user_password }}"
            login_port: "{{ mongod_port }}"

        - import_tasks: ../shared_tasks/upgrade_mongod.yml

        - name: Validate the replicaset state again
          community.mongodb.mongodb_status:
            login_user: "{{ admin_user }}"
            login_password: "{{ admin_user_password }}"
            login_port: "{{ mongod_port }}"
            poll: 3
            interval: 10
      when: inventory_hostname_short == primary

- name: Upgrade SECONDARY mongod servers for rs0
  hosts: rs0
  gather_facts: yes
  become: yes
  serial: 1
  vars_files:
    - ../vars/main.yml
    - ../sharded_cluster/vault.yml
  vars:
    required_packages:
      - "yum-plugin-versionlock"
    current_mongodb_version: "4.2"
    target_mongodb_version: "4.4"
    rs: "rs0"

  # Process is based on the following offical documentation...
  # https://docs.mongodb.com/manual/release-notes/4.2-upgrade-sharded-cluster/
  tasks:

    - name: Set port for mongod shard servers
      set_fact:
        mongod_port: 27018

    - import_tasks: ../shared_tasks/get_primary.yml

    - name: Upgrade SECONDARY MongoDB hosts first for r0
      block:
        - import_tasks: ../shared_tasks/upgrade_mongod.yml

        - name: Ensure that current replicaset state is good
          community.mongodb.mongodb_status:
            login_user: "{{ admin_user }}"
            login_password: "{{ admin_user_password }}"
            login_port: "{{ mongod_port }}"
            replica_set: "{{ repl_set_name }}"
            poll: 3
            interval: 10
      when: inventory_hostname_short != primary

- name: Upgrade PRIMARY mongod server for rs0
  hosts: rs0
  gather_facts: yes
  become: yes
  vars_files:
    - ../vars/main.yml
    - ../sharded_cluster/vault.yml
  vars:
    required_packages:
      - "yum-plugin-versionlock"
    current_mongodb_version: "4.2"
    target_mongodb_version: "4.4"
    rs: "rs0"

  tasks:

    - name: Set port for mongod shard servers
      set_fact:
        mongod_port: 27018

    - import_tasks: ../shared_tasks/get_primary.yml

    - name: Upgrade PRIMARY MongoDB Host for rs0
      block:
        - name: Stepdown if primary
          community.mongodb.mongodb_stepdown:
            login_user: "{{ admin_user }}"
            login_password: "{{ admin_user_password }}"
            login_port: "{{ mongod_port }}"

        - import_tasks: ../shared_tasks/upgrade_mongod.yml

        - name: Validate the replicaset state again
          community.mongodb.mongodb_status:
            login_user: "{{ admin_user }}"
            login_password: "{{ admin_user_password }}"
            login_port: "{{ mongod_port }}"
            poll: 3
            interval: 10
      when: inventory_hostname_short == primary

- name: Upgrade SECONDARY mongod servers for rs1
  hosts: rs1
  gather_facts: yes
  become: yes
  serial: 1
  vars_files:
    - ../vars/main.yml
    - ../sharded_cluster/vault.yml
  vars:
    required_packages:
      - "yum-plugin-versionlock"
    current_mongodb_version: "4.2"
    target_mongodb_version: "4.4"
    rs: "rs1"

  # Process is based on the following offical documentation...
  # https://docs.mongodb.com/manual/release-notes/4.2-upgrade-sharded-cluster/
  tasks:

    - name: Set port for mongod shard servers
      set_fact:
        mongod_port: 27018

    - import_tasks: ../shared_tasks/get_primary.yml

    - name: Patch SECONDARY MongoDB hosts first for r1
      block:
        - import_tasks: ../shared_tasks/upgrade_mongod.yml

        - name: Ensure that current replicaset state is good
          community.mongodb.mongodb_status:
            login_user: "{{ admin_user }}"
            login_password: "{{ admin_user_password }}"
            login_port: "{{ mongod_port }}"
            replica_set: "{{ repl_set_name }}"
            poll: 3
            interval: 10
      when: inventory_hostname_short != primary

- name: Upgrade PRIMARY mongod server for rs1
  hosts: rs1
  gather_facts: yes
  become: yes
  vars_files:
    - ../vars/main.yml
    - ../sharded_cluster/vault.yml
  vars:
    required_packages:
      - "yum-plugin-versionlock"
    current_mongodb_version: "4.2"
    target_mongodb_version: "4.4"
    rs: "rs1"

  tasks:

    - name: Set port for mongod shard servers
      set_fact:
        mongod_port: 27018

    - import_tasks: ../shared_tasks/get_primary.yml

    - name: Upgrade PRIMARY MongoDB Host for rs1
      block:
        - name: Stepdown if primary
          community.mongodb.mongodb_stepdown:
            login_user: "{{ admin_user }}"
            login_password: "{{ admin_user_password }}"
            login_port: "{{ mongod_port }}"

        - import_tasks: ../shared_tasks/upgrade_mongod.yml

        - name: Validate the replicaset state again
          community.mongodb.mongodb_status:
            login_user: "{{ admin_user }}"
            login_password: "{{ admin_user_password }}"
            login_port: "{{ mongod_port }}"
            poll: 3
            interval: 10
      when: inventory_hostname_short == primary

- name: Upgrade the mongos instances
  hosts: mongos
  gather_facts: yes
  become: yes
  serial: 1
  vars_files:
    - ../vars/main.yml
    - ../sharded_cluster/vault.yml
  vars:
    required_packages:
      - "yum-plugin-versionlock"
    current_mongodb_version: "4.2"
    target_mongodb_version: "4.4"

  # Process is based on the following offical documentation...
  # https://docs.mongodb.com/manual/release-notes/4.2-upgrade-sharded-cluster/
  tasks:

    - import_tasks: ../shared_tasks/upgrade_mongos.yml

- name: Enable the Balancer
  hosts: mongos
  vars_files:
    - ../vars/main.yml
    - ../sharded_cluster/vault.yml

  tasks:

    - name: Enable the Balancer
      community.mongodb.mongodb_balancer:
        state: started
        login_user: "{{ admin_user }}"
        login_password: "{{ admin_user_password }}"
        login_port: "{{ mongos_port }}"
      run_once: yes
