---
- name: Prep the MongoDB Cluster for downgrade
  hosts: mongos
  any_errors_fatal: true
  vars_files:
    - ../vars/main.yml
    - ../sharded_cluster/vault.yml

  tasks:

  # Process is based on the following offical documentation...
  # https://docs.mongodb.com/manual/release-notes/4.2-downgrade-sharded-cluster/
    - name: Disable the Balancer
      community.mongodb.mongodb_balancer:
        state: stopped
        login_user: "{{ admin_user }}"
        login_password: "{{ admin_user_password }}"
        login_port: "{{ mongos_port }}"
      run_once: yes

    - name: Set featureCompatibilityVersion to 4.0
      community.mongodb.mongodb_shell:
        login_user: "{{ admin_user }}"
        login_password: "{{ admin_user_password }}"
        login_port: "{{ mongos_port }}"
        eval: "db.adminCommand({setFeatureCompatibilityVersion: '4.0'})"
      run_once: yes

    - name: Drop the user_1_db_1 on the system.users collection
      community.mongodb.mongodb_index:
        login_user: "{{ admin_user }}"
        login_password: "{{ admin_user_password }}"
        login_host: "{{ item.host }}"
        login_port: "{{ item.port }}"
        replica_set: "{{ item.rs }}"
        indexes:
          - database: "admin"
            collection: "system.users"
            options:
              name: "user_1_db_1"
            state: "absent"
      with_items:
        - host: "mongos1.local"
          port: "{{ mongos_port }}"
          rs: null
        - host: "mongodb1.local"
          port: "27018"
          rs: "rs0"
        - host: "mongodb4.local"
          port: "27018"
          rs: "rs1"
      run_once: yes

- name: Downgrade the mongos instances
  hosts: mongos
  gather_facts: yes
  become: yes
  serial: 1
  vars_files:
    - ../vars/main.yml
    - ../sharded_cluster/vault.yml
  vars:
    required_packages:
      - "yum-plugin-versionlock"
    current_mongodb_version: "4.2"
    target_mongodb_version: "4.0"

  tasks:

    - name: Downgrade the mongos package
      set_fact:
        mongodb_downgrade: true

    - import_tasks: ../shared_tasks/upgrade_mongos.yml

- name: Downgrade SECONDARY mongod servers for rs0
  hosts: rs0
  gather_facts: yes
  become: yes
  serial: 1
  vars_files:
    - ../vars/main.yml
    - ../sharded_cluster/vault.yml
  vars:
    required_packages:
      - "yum-plugin-versionlock"
    current_mongodb_version: "4.2"
    target_mongodb_version: "4.0"
    rs: "rs0"


  # Process is based on the following offical documentation...
  # https://docs.mongodb.com/manual/release-notes/4.4-downgrade-sharded-cluster/
  # Always take a backup before running this playbook and ensure you've read the documentation
  # regarding incompatible configuration settings that may caue problems during a downgrade.
  tasks:

    - name: Set port for mongod shard servers
      set_fact:
        mongod_port: 27018

    - import_tasks: ../shared_tasks/get_primary.yml

    - name: Downgrade SECONDARY MongoDB hosts first
      block:
        - name: Downgrade the mongod package
          set_fact:
            mongodb_downgrade: true

        - import_tasks: ../shared_tasks/upgrade_mongod.yml

        - name: Ensure that current replicaset state is good
          community.mongodb.mongodb_status:
            login_user: "{{ admin_user }}"
            login_password: "{{ admin_user_password }}"
            login_port: "{{ mongod_port }}"
            replica_set: "{{ repl_set_name }}"
            poll: 3
            interval: 10
      when: inventory_hostname_short != primary

- name: Downgrade PRIMARY mongod server for rs0
  hosts: rs0
  gather_facts: yes
  become: yes
  vars_files:
    - ../vars/main.yml
    - ../sharded_cluster/vault.yml
  vars:
    required_packages:
      - "yum-plugin-versionlock"
    current_mongodb_version: "4.2"
    target_mongodb_version: "4.0"
    rs: "rs0"

  tasks:

    - name: Set port for mongod shard servers
      set_fact:
        mongod_port: 27018

    - import_tasks: ../shared_tasks/get_primary.yml

    - name: Upgrade PRIMARY MongoDB member
      block:
        - name: Stepdown if primary
          community.mongodb.mongodb_stepdown:
            login_user: "{{ admin_user }}"
            login_password: "{{ admin_user_password }}"
            login_port: "{{ mongod_port }}"

        - name: Downgrade the mongod package
          set_fact:
            mongodb_downgrade: true

        - import_tasks: ../shared_tasks/upgrade_mongod.yml

        - name: Validate the replicaset state again
          community.mongodb.mongodb_status:
            login_user: "{{ admin_user }}"
            login_password: "{{ admin_user_password }}"
            login_port: "{{ mongod_port }}"
            poll: 3
            interval: 10
      when: inventory_hostname_short == primary

- name: Downgrade SECONDARY mongod servers for rs1
  hosts: rs1
  gather_facts: yes
  become: yes
  serial: 1
  vars_files:
    - ../vars/main.yml
    - ../sharded_cluster/vault.yml
  vars:
    required_packages:
      - "yum-plugin-versionlock"
    current_mongodb_version: "4.2"
    target_mongodb_version: "4.0"
    rs: "rs1"

  # Process is based on the following offical documentation...
  # https://docs.mongodb.com/manual/release-notes/4.4-downgrade-sharded-cluster/
  # Always take a backup before running this playbook and ensure you've read the documentation
  # regarding incompatible configuration settings that may caue problems during a downgrade.
  tasks:

    - name: Set port for mongod shard servers
      set_fact:
        mongod_port: 27018

    - import_tasks: ../shared_tasks/get_primary.yml

    - name: Downgrade SECONDARY MongoDB hosts first
      block:
        - name: Downgrade the mongod package
          set_fact:
            mongodb_downgrade: true

        - import_tasks: ../shared_tasks/upgrade_mongod.yml

        - name: Ensure that current replicaset state is good
          community.mongodb.mongodb_status:
            login_user: "{{ admin_user }}"
            login_password: "{{ admin_user_password }}"
            login_port: "{{ mongod_port }}"
            replica_set: "{{ repl_set_name }}"
            poll: 3
            interval: 10
      when: inventory_hostname_short != primary

- name: Downgrade PRIMARY mongod server for rs1
  hosts: rs1
  gather_facts: yes
  become: yes
  vars_files:
    - ../vars/main.yml
    - ../sharded_cluster/vault.yml
  vars:
    required_packages:
      - "yum-plugin-versionlock"
    current_mongodb_version: "4.2"
    target_mongodb_version: "4.0"
    rs: "rs1"

  tasks:

    - name: Set port for mongod shard servers
      set_fact:
        mongod_port: 27018

    - import_tasks: ../shared_tasks/get_primary.yml

    - name: Upgrade PRIMARY MongoDB member
      block:
        - name: Stepdown if primary
          community.mongodb.mongodb_stepdown:
            login_user: "{{ admin_user }}"
            login_password: "{{ admin_user_password }}"
            login_port: "{{ mongod_port }}"

        - name: Downgrade the mongod package
          set_fact:
            mongodb_downgrade: true

        - import_tasks: ../shared_tasks/upgrade_mongod.yml

        - name: Validate the replicaset state again
          community.mongodb.mongodb_status:
            login_user: "{{ admin_user }}"
            login_password: "{{ admin_user_password }}"
            login_port: "{{ mongod_port }}"
            poll: 3
            interval: 10
      when: inventory_hostname_short == primary

- name: Prep the MongoDB Config servers for downgrade
  hosts: mongos
  gather_facts: yes
  become: yes
  serial: 1
  vars_files:
    - ../vars/main.yml
    - ../sharded_cluster/vault.yml
  vars:
    required_packages:
      - "yum-plugin-versionlock"
    current_mongodb_version: "4.2"
    target_mongodb_version: "4.0"

  tasks:

        - name: Ensure the admin user has the correct configdb perms
          import_tasks: ../shared_tasks/configdb_role.yml

        - name: Drop indexes on the various collections for the dg
          community.mongodb.mongodb_index:
            login_user: "{{ admin_user }}"
            login_password: "{{ admin_user_password }}"
            login_port: 27019
            replica_set: "cfg"
            indexes:
              - database: "{{ item.db }}"
                collection: "{{ item.collection }}"
                options:
                  name: "{{ item.index }}"
                state: "absent"
          with_items:
            - db: "config"
              collection: "chunks"
              index: "ns_1_min_1"
            - db: "config"
              collection: "chunks"
              index: "ns_1_shard_1_min_1"
            - db: "config"
              collection: "chunks"
              index: "ns_1_lastmod_1"
            - db: "config"
              collection: "migrations"
              index: "ns_1_min_1"
            - db: "config"
              collection: "shards"
              index: "host_1"
            - db: "config"
              collection: "tags"
              index: "ns_1_min_1"
            - db: "config"
              collection: "tags"
              index: "ns_1_tag_1"
            - db: "config"
              collection: "tags"
              index: "ns_1_min_1"
          run_once: yes

        - name: Short pause to allow secondaries to catch up
          pause:
            seconds: 5

- name: Downgrade the SECONDARY mongod config servers
  hosts: mongos
  gather_facts: yes
  become: yes
  serial: 1
  vars_files:
    - ../vars/main.yml
    - ../sharded_cluster/vault.yml
  vars:
    required_packages:
      - "yum-plugin-versionlock"
    current_mongodb_version: "4.2"
    target_mongodb_version: "4.0"

  # Process is based on the following offical documentation...
  # https://docs.mongodb.com/manual/release-notes/4.2-upgrade-sharded-cluster/
  tasks:

    - name: Set mongod_port to 27019
      set_fact:
        mongod_port: 27019

    - name: Downgrade the mongod package
      set_fact:
        mongodb_downgrade: true

    - import_tasks: ../shared_tasks/get_primary.yml

    - name: Upgrade SECONDARY config servers first
      block:

        - import_tasks: ../shared_tasks/upgrade_mongod.yml

        - name: Ensure that current replicaset state is good
          community.mongodb.mongodb_status:
            login_user: "{{ admin_user }}"
            login_password: "{{ admin_user_password }}"
            login_port: "{{ mongod_port }}"
            replica_set: "{{ repl_set_name }}"
            poll: 3
            interval: 10
      when: inventory_hostname_short != primary

- name: Downgrade the PRIMARY mongod config server
  hosts: mongos
  gather_facts: yes
  become: yes
  vars_files:
    - ../vars/main.yml
    - ../sharded_cluster/vault.yml
  vars:
    required_packages:
      - "yum-plugin-versionlock"
    current_mongodb_version: "4.2"
    target_mongodb_version: "4.0"

  tasks:

    - name: Set mongod_port to 27019
      set_fact:
        mongod_port: 27019

    - name: Downgrade the mongod package
      set_fact:
        mongodb_downgrade: true

    - import_tasks: ../shared_tasks/get_primary.yml

    - name: Upgrade PRIMARY Config Server
      block:

        - name: Stepdown primary
          community.mongodb.mongodb_stepdown:
            login_user: "{{ admin_user }}"
            login_password: "{{ admin_user_password }}"
            login_port: "{{ mongod_port }}"

        - import_tasks: ../shared_tasks/upgrade_mongod.yml

        - name: Validate the replicaset state again
          community.mongodb.mongodb_status:
            login_user: "{{ admin_user }}"
            login_password: "{{ admin_user_password }}"
            login_port: "{{ mongod_port }}"
            poll: 3
            interval: 10
      when: inventory_hostname_short == primary

- name: Enable the Balancer
  hosts: mongos
  vars_files:
    - ../vars/main.yml
    - ../sharded_cluster/vault.yml

  tasks:

    - name: Enable the Balancer
      community.mongodb.mongodb_balancer:
        state: started
        autosplit: yes
        login_user: "{{ admin_user }}"
        login_password: "{{ admin_user_password }}"
        login_port: "{{ mongos_port }}"
      run_once: yes
