---
- hosts: all
  gather_facts: yes
  become: yes
  serial: 1
  vars_files:
    - ../vars/main.yml
    - ../replicaset/vault.yml
  vars:
    sync_timeout: 900

  tasks:

    - name: End play if mongodb_members > 1
      meta: end_play
      when: ansible_play_hosts | length > 1

    - name: RedHat 8 in docker fix
      import_tasks: ../shared_tasks/redhat8_docker_fix.yml
      tags:
        - never

    - name: Ensure mongod_data_dir variable is correct
      lineinfile:
        path: /etc/mongod.conf
        regexp: ".*{{ mongod_data_dir }}.*"
        state: present
      check_mode: yes
      register: data_dir_valid
      failed_when: data_dir_valid.changed

    - name: Shutdown mongod
      community.mongodb.mongodb_shutdown:
        login_user: "{{ admin_user }}"
        login_password: "{{ admin_user_password }}"

    - name: RedHat 8 in docker force stop (pidfile missing)
      import_tasks: ../shared_tasks/redhat8_docker_force_stop.yml
      tags:
        - never

    - name: Archive data dir
      archive:
        path: "{{ mongod_data_dir }}"
        dest: /var/lib/mongod.tar.gz

    - name: Delete files in data dir
      shell: "rm -rf {{ mongod_data_dir }}/*"

    - name: Start the mongod process
      service:
        name: "{{ mongod_service }}"
        state: started

    - name: Wait for initial sync done log msg
      wait_for:
        path: "/var/log/mongodb/mongod.log"
        search_regex: "initial sync done"
        timeout: "{{ sync_timeout }}"

    - name: Wait for mongod to become responsive
      wait_for:
        port: "{{ mongod_port }}"
        delay: 10

    - name: Validate replicaset state
      community.mongodb.mongodb_status:
        login_user: "{{ admin_user }}"
        login_password: "{{ admin_user_password }}"
        poll: 3
        interval: 10
