Vagrant.configure("2") do |config|
  MONGOD_HOSTS=3
  (1..MONGOD_HOSTS).each do |mongod|
    node_name = "mongodb-#{mongod}"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vbguest.installer_options = { allow_kernel_upgrade: true }
    config.vm.define node_name do |mongod_node|
      mongod_node.vm.box = "centos/8"
      mongod_node.vm.network "private_network", ip: "192.168.56.#{200 + mongod}"
      mongod_node.vm.hostname = node_name
      mongod_node.vm.provider :virtualbox do |vbox|
        vbox.linked_clone = true
        vbox.name = node_name
      end

      config.vm.provision "allow_guest_host_resolution",
          type: "shell",
          inline: 'yum install -y epel-release; yum install -y avahi nss-mdns systemd; systemctl restart avahi-daemon'

      if mongod == MONGOD_HOSTS
        mongod_node.vm.provision :ansible do |ansible|
          ansible.groups = {
            "mongodb" => ["mongodb-1","mongodb-2","mongodb-3"],
          }
          ansible.raw_arguments = "--ask-vault-pass"
          ansible.limit = "all" # Connect to all mongodb hosts
          ansible.become = true
          ansible.playbook = "mongodb.yml"
        end
      end
    end
  end
end
