Vagrant.configure("2") do |config|
    node_name = "mongodb"
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vbguest.installer_options = { allow_kernel_upgrade: true }
    config.vm.define node_name do |mongod_node|
      mongod_node.vm.box = "centos/8"
      mongod_node.vm.network "private_network", ip: "192.168.43.244"
      mongod_node.vm.hostname = node_name
      config.vm.provider "virtualbox" do |v|
        v.memory = 4192
        v.cpus = 2
      end
      config.vm.provision "allow_guest_host_resolution",
          type: "shell",
          inline: 'yum install -y epel-release; yum install -y avahi nss-mdns; systemctl restart avahi-daemon'

        mongod_node.vm.provision :ansible do |ansible|
          ansible.raw_arguments = "--ask-vault-pass"
          ansible.limit = "all" # Connect to all mongodb hosts
          ansible.become = true
          ansible.playbook = "mongodb.yml"
        end
      end
end
